const ProjectActionTypes = {
  FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
  CLEAR_PROJECTS: 'CLEAR_PROJECTS',
};

export default  ProjectActionTypes;